import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';


import {OwlDateTimeModule, OwlNativeDateTimeModule} from 'ng-pick-datetime';
import {
    MatAutocompleteModule,
    MatBadgeModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule, MatDividerModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatSelectModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatSortModule,
    MatStepperModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    MatRippleModule
} from "@angular/material";
import { ScrollingModule, ScrollDispatchModule } from '@angular/cdk/scrolling';
import {DragDropModule} from '@angular/cdk/drag-drop';
import {Ng2FabSpeedDialModule} from 'ng2-fab-speed-dial';
import { TextFieldModule } from '@angular/cdk/text-field';
@NgModule({
    imports: [
        CommonModule,
        MatButtonModule,
        MatCardModule,
        MatSortModule,
        MatTableModule,
        MatInputModule,
        MatPaginatorModule,
        MatSelectModule,
        MatCheckboxModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatStepperModule,
        MatRadioModule,
        MatProgressSpinnerModule,
        MatExpansionModule,
        MatSidenavModule,
        MatListModule,
        MatFormFieldModule,
        MatIconModule,
        MatTooltipModule,
        MatToolbarModule,
        MatMenuModule,
        MatButtonToggleModule,
        MatGridListModule,
        MatSlideToggleModule,
        MatDialogModule,
        MatChipsModule,
        MatTabsModule,
        OwlDateTimeModule,
        OwlNativeDateTimeModule,
        MatAutocompleteModule,
        MatBadgeModule,
        MatDividerModule,
        MatRippleModule,
        ScrollingModule,
        // ScrollDispatchModule,
        DragDropModule,
        Ng2FabSpeedDialModule,
        TextFieldModule
    ],
    declarations: [],
    exports: [
        MatButtonModule,
        MatCardModule,
        MatSortModule,
        MatTableModule,
        MatInputModule,
        MatPaginatorModule,
        MatSelectModule,
        MatCheckboxModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatStepperModule,
        MatRadioModule,
        MatProgressSpinnerModule,
        MatExpansionModule,
        MatSidenavModule,
        MatListModule,
        MatFormFieldModule,
        MatIconModule,
        MatTooltipModule,
        MatToolbarModule,
        MatMenuModule,
        MatButtonToggleModule,
        MatGridListModule,
        MatSlideToggleModule,
        MatDialogModule,
        MatChipsModule,
        MatTabsModule,
        OwlDateTimeModule,
        OwlNativeDateTimeModule,
        MatAutocompleteModule,
        MatBadgeModule,
        MatDividerModule,
        MatRippleModule,
        ScrollingModule,
        // ScrollDispatchModule,
        DragDropModule,
        Ng2FabSpeedDialModule,
        TextFieldModule
    ]
})
export class MaterialModule {
}
